sudo: required

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get -y update ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get -y install git ; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo add-apt-repository --yes ppa:kalakris/cmake ; fi

install:
  - ./install-dependencies.sh
  - ./setup.sh
  - ./build.sh
  - ./install-example-application-dependencies.sh

script:
  - source setup-env.sh
  - python test/runtest.py
  - python test/array_test.py
  - python examples/lbfgs/driver.py
