sudo: required

language: generic

services:
  - docker

install:
  - tar --exclude './docker' --exclude './.git' -cv . > ./docker/test-base/ray.tar
  - docker build --no-cache -t amplab/ray:test-base docker/test-base
  - rm ./docker/test-base/ray.tar
  - docker build --no-cache -t amplab/ray:test-examples docker/test-examples
  - docker ps -a


script:
  - docker run amplab/ray:test-base bash -c 'source setup-env.sh && cd test && python runtest.py && python array_test.py && python microbenchmarks.py'
  - docker run --shm-size=500m amplab/ray:test-examples bash -c 'source setup-env.sh && cd examples/lbfgs && python driver.py'
  - docker run --shm-size=500m amplab/ray:test-examples bash -c 'source setup-env.sh && cd examples/hyperopt && python driver.py'
